import { useEffect, useState } from 'react'
import { createProposal, listProposals, updateProposal } from '../api/proposals'
import { getTaskRating } from '../api/tasks'
import ReadinessScore from '../components/ReadinessScore'

const detailFields = ['title', 'context', 'need', 'users', 'data_materials', 'constraints', 'expected_result', 'success_criteria', 'contact', 'interaction_format', 'topic']
export default function TaskDetail({ task, taskId }) {
  const id = taskId || task?.id; const [proposals, setProposals] = useState([]); const [rating, setRating] = useState(null); const [form, setForm] = useState({ team_id: '', idea: '', plan: '', deadline: '', link: '' }); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (!id) return; Promise.all([listProposals(id), getTaskRating(id)]).then(([items, score]) => { setProposals(items); setRating(score) }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)) }, [id])
  if (!id) return <p>Provide a task id.</p>
  async function submit(event) { event.preventDefault(); setSubmitting(true); setError(''); try { const value = await createProposal(id, { ...form, team_id: Number(form.team_id), plan: form.plan || null, deadline: form.deadline || null, link: form.link || null }); setProposals((current) => [...current, value]); setForm({ team_id: '', idea: '', plan: '', deadline: '', link: '' }) } catch (reason) { setError(reason.message) } finally { setSubmitting(false) } }
  async function setStatus(proposal, status) { try { const value = await updateProposal(proposal.id, status); setProposals((current) => current.map((item) => item.id === value.id ? value : item)) } catch (reason) { setError(reason.message) } }
  return <section><h1>{task?.title || `Task #${id}`}</h1>{error && <p role="alert">{error}</p>}{detailFields.map((field) => task?.[field] && <p key={field}><strong>{field}:</strong> {task[field]}</p>)}<ReadinessScore task={task} rating={rating} /><h2>Submit proposal</h2><form onSubmit={submit}>{Object.keys(form).map((field) => <label key={field}>{field}<input required={field === 'team_id' || field === 'idea'} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} /></label>)}<button disabled={submitting}>{submitting ? 'Submitting…' : 'Submit proposal'}</button></form><h2>Proposals</h2>{loading && <p>Loading proposals…</p>}{!loading && proposals.length === 0 && <p>No proposals yet.</p>}<ul>{proposals.map((proposal) => <li key={proposal.id}><strong>{proposal.idea}</strong> — team {proposal.team_id} — {proposal.status}<p>{proposal.plan}</p>{proposal.link && <p><a href={proposal.link}>{proposal.link}</a></p>}{proposal.status === 'pending' && <><button onClick={() => setStatus(proposal, 'accepted')}>Accept</button><button onClick={() => setStatus(proposal, 'rejected')}>Reject</button></>}</li>)}</ul></section>
}
